---
title: "Test for difference in Means"
author: "Anna Talucci"
date: "1/27/2024"
output: html_document
---

# Overview
Test for differences in means between groups at different time steps.

# Packages
```{r}
library(tidyverse)
library(emmeans) 

library(statmod)
library(car)

library(MASS)
#library(cplm)
library(aod)
```


# Data

```{r}
fvs = read_csv("../data/FVS/FVSprocessedOutputsHucs.csv")
```

```{r}
fvs
```

# Create Group ID
```{r}
( fvs1 = fvs %>% group_by(RRK, Priority, TxIntensity, TxType, Year) %>% 
    mutate(group_id = cur_group_id()) %>%
    mutate(groupName = paste(RRK,"_", Priority, "_", TxIntensity, "_", TxType, "_", Year))
  )
```

```{r}
unique(fvs1$group_id)
```

```{r}
( WUICCchange20 = fvs1 %>% 
    filter(Year %in% c(2024, 2044)) %>%
    filter(Priority=="WUI") %>%
    filter(TxIntensity %in% c("500k", "2m")) %>%
    filter(RRK=="CC")
  )
```

```{r}
unique(WUIchange20$groupName)
```
# Test for differences in Means at 20 years
```{r}
fit1 = lm(TSC ~ groupName, data = WUICCchange20)
```

```{r}

```


```{r}
( emm1 = emmeans(fit1, specs = pairwise ~ groupName) )
```

```{r}
emm1$emmeans
emm1$contrasts
```

```{r}
emmeans(fit1, specs = pairwise ~ groupName, type = "response")
```

```{r}
emm1.1 = emmeans(fit1, specs = pairwise ~ groupName, type = "response", adjust = "none")
emm1.1
```

```{r}
emm1.1$contrasts %>%
     confint()

emm1.1$contrasts %>%
     summary(infer = TRUE)

emm1.1$emmeans %>%
     as.data.frame()
```

```{r}
emm2 = emmeans(fit1, specs = pairwise ~ groupName, type = "response")
emm2
```


emm2$contrasts %>%
     rbind() 


