---
title: "Rank Percent Check"
output: html_document
---

# Overview
Calculate check for min max of percent rank, error in calculation

Note: found error in EE code and fixed.


# Packages
```{r}
library(tidyverse)
library(skimr)
library(sf)
```

# Data
```{r}
rank = read.csv("../data/csv/snHucTreat10WuiBpPrctRk_2023-04-29.csv")
```
```{r}
cc = st_read("../data/EEhucs/ccHucTreat10WuiBpPrctRk_2023-04-29.shp", "ccHucTreat10WuiBpPrctRk_2023-04-29")
```

# Look at data

```{r}
glimpse(rank)
```


```{r}
skimr::skim(rank)
```
 mutate(across(cols, round, 3))
```{r}
rank %>% 
  dplyr::select(BpMean:RRK_Region, WIPGeoNam:areasqkm, huc12, name, states:sumsqkm) %>%
  mutate(across(c(BpMean, BpPrct, PropTreat, PropWui, WuiPrct, sum, sumsqkm), round, 3)) %>%
  summarize(minBpPrct = min(BpPrct),
            maxBpPrct = max(BpPrct),
            minWuiPrct = min(WuiPrct),
            maxWuiPrct = max(WuiPrct),
            minBpRank = min(BpRank),
            maxBpRank = max(BpRank),
            minWuiRank = min(WuiRank),
            maxWuiRank = max(WuiRank),)
```


```{r}


```

```{r}
cc %>% 
  st_drop_geometry(.) %>%
  dplyr::select(BpMean:RRK_Region, WIPGeoNam:areasqkm, huc12, name, states:sumsqkm) %>%
  mutate(across(c(BpMean, BpPrct, PropTreat, PropWui, WuiPrct, sum, sumsqkm), round, 3)) %>%
  summarize(minBpPrct = min(BpPrct),
            maxBpPrct = max(BpPrct),
            minWuiPrct = min(WuiPrct),
            maxWuiPrct = max(WuiPrct),
            minBpRank = min(BpRank),
            maxBpRank = max(BpRank),
            minWuiRank = min(WuiRank),
            maxWuiRank = max(WuiRank),)
```