---
title: "Road Grid"
author: "Anna Talucci"
date: "7/16/2023"
output: html_document
---

# Packages
```{r}
library(tidyverse)
library(sf)
library(terra)
```

# Data
## hucs
```{r}
hucs = st_read("../data/TxHucs/TxPrctRankRrkWipRffc.shp", "TxPrctRankRrkWipRffc")
```

```{r}
hucs
```
## RRK
```{r}
rrk = st_read("../data/RRK/RRK_boundaries3.shp", "RRK_boundaries3")
```
```{r}
rrk
```
## Raod
```{r}
roads = st_read("../data/roads/tl_2019_us_primaryroads/tl_2019_us_primaryroads.shp", "tl_2019_us_primaryroads")
```

```{r}
roadps = st_read("../data/roads/tl_2016_06_prisecroads/tl_2016_06_prisecroads.shp", "tl_2016_06_prisecroads")
```
```{r}
roadps
```

```{r}
roadsc = st_read("../data/roads/ee/scRoad.shp", "scRoad")
```
```{r}
roadcc = st_read("../data/roads/ee/ccRoad.shp", "ccRoad")
```
# Filter RRK
```{r}
sc = rrk %>% filter(RRK_Region=="South Coast Region")
cc = rrk %>% filter(RRK_Region=="Central Coast Region")
```

# Filter Hucs
```{r}
hucs
```
```{r}
ccHucs = hucs %>% filter(RRK_Rgn =="Central Coast Region") %>% dplyr::select(huc12, RRK_Rgn)
scHucs = hucs %>% filter(RRK_Rgn =="South Coast Region") %>% dplyr::select(huc12, RRK_Rgn)
```
# Reproject 
```{r}
roadps = st_transform(roadps, crs = "EPSG:3310")
roadsc = st_transform(roadsc, crs = "EPSG:3310")
roadcc = st_transform(roadcc, crs = "EPSG:3310")
sc = st_transform(sc, crs = "EPSG:3310")
cc = st_transform(cc, crs = "EPSG:3310")

scHucs = st_transform(scHucs, crs = "EPSG:3310")
ccHucs= st_transform(ccHucs, crs = "EPSG:3310")
```

## Check projections match
```{r}
st_crs(sc) == st_crs(roadsc)
```
```{r}
st_crs(cc) == st_crs(roadps)
```
```{r}
road = roadsc
```
# Create and select Grid for roads
```{r}
scGridRd <- st_make_grid(sc, square = T, cellsize = c(636.1494, 636.1494))%>%
  cbind(data.frame(ID = sprintf(paste("GID%0",nchar(length(.)),"d",sep=""), 1:length(.)))) %>%
  st_sf() %>% 
  st_cast('POLYGON') %>%
  st_join(., road, largest=TRUE) %>% 
  drop_na(linearid)

```

```{r}
sqrt(404686)
```

```{r}
length(unique(scGridRd$ID))
```
```{r}
scGridRd
```

```{r}
ccGridRd <- st_make_grid(cc, square = T, cellsize = c(636.1494, 636.1494)) %>%
  cbind(data.frame(ID = sprintf(paste("GID%0",nchar(length(.)),"d",sep=""), 1:length(.)))) %>%
  st_sf() %>% 
  st_cast('POLYGON') %>%
  st_join(., roadcc, largest=TRUE) %>% 
  drop_na(linearid)

```

```{r}
length(unique(ccGridRd$ID))
```
```{r}
ccGridRd
```
## check data
```{r}
class(scGridRd)
scGridRd
```

```{r}
class(ccGridRd)
ccGridRd
```
## Plot
```{r eval=FALSE, include=FALSE}
ggplot() + geom_sf(data = scGridRd) + 
  theme_bw()
```

# Select grids for Tx Hucs
```{r}
( ccTxGrid = st_join(ccGridRd, ccHucs, largest=TRUE))
```

```{r}
( scTxGrid = st_join(scGridRd, scHucs, largest=TRUE))
```

```{r}
scTxGrid1 = scTxGrid %>% drop_na(huc12)
ccTxGrid1 = ccTxGrid %>% drop_na(huc12)
```
```{r}
nrow(scGridRd)
nrow(scTxGrid1)
nrow(ccGridRd)
nrow(ccTxGrid1)
```

# Define projection
```{r}
projection = st_crs(rrk)
```

# Reproject
```{r}
ccTxGrid2 = st_transform(ccTxGrid1, projection)
scTxGrid2 = st_transform(scTxGrid1, projection)
```

```{r}
ccTxGrid2
scTxGrid2
```

# Write to shapefile

```{r eval=FALSE, include=FALSE}
st_write(ccTxGrid2, "../outputs/GridRoad/ccTxGridRoad.shp", driver="ESRI Shapefile")
```

```{r eval=FALSE, include=FALSE}
st_write(scTxGrid2, "../outputs/GridRoad/scTxGridRoad.shp", driver="ESRI Shapefile")
```