---
title: "Select Hucs with 50% overlap"
output: html_document
---

# Overview

# Packages
```{r}
library(tidyverse)
library(sf)
```

# Data
## RRK
```{r}
rrk = st_read("../data/RRK/RRK_boundaries3.shp", "RRK_boundaries3")
```

## HUC12
```{r}
hucs = st_read("../data/USGS_HUC12/AllHucs.shp", "AllHucs")
```


## States
```{r}
states = st_read("../data/State_boundaries/tl_2022_us_state.shp", "tl_2022_us_state")
```

## WIP
```{r}
wip = st_read("../data/WIP_Regions/WIP_Regions.shp", "WIP_Regions")
```
# SN
```{r}
sn = st_read("../data/sn/SN.shp", "SN")
```
# Plots
```{r}
plot(st_geometry(hucs))
```

# Select States
```{r}
(
  states_aoi = states %>% filter(NAME %in% c("California", "Oregon", "Nevada", "Arizona"))
)
```

# Define projection
```{r}
projection = st_crs(rrk)
```

# Reproject HUCs
```{r}
hucs_ab = st_transform(hucs, projection)
```

```{r}
states_ab = st_transform(states_aoi, projection)
```

```{r}
wip_ab = st_transform(wip, projection)
```

# Calculate Huc Area
```{r}
( hucs_area = hucs_ab %>% 
  dplyr::mutate(huc_sqm = as.numeric(st_area(hucs_ab))) %>%
                # 1 m2 = 0.0.000247105 acres
  dplyr::mutate(huc_acres = as.numeric(huc_sqm * 0.000247105)) %>%
                # 1m2 = 0.0001 hectares
  dplyr::mutate(huc_hectares = as.numeric(huc_sqm * 0.0001))
)
```

# Plot
```{r}
plot(st_geometry(rrk))
plot(st_geometry(wip_ab),col="red", add=TRUE)
```

```{r}
plot(st_geometry(sn))
plot(st_geometry(wip_ab),col="red", add=TRUE)
```

# Join Hucs with states
st_join(st_make_valid(data1), ren_ecozones_ea, largest=TRUE) 4473
```{r}
( joinHucstate = st_join(st_make_valid(hucs_ab), st_make_valid(states_ab), largest=TRUE))
```
# Remove HUCs not assigned to California
```{r}
(
  caHucs = joinHucstate %>% filter(NAME=="California")
)
```

## Join HUC with RRK
```{r}
( joinHucRrk = st_join(caHucs, rrk, largest=TRUE))
```

## Join WIPS to HUCs
```{r}
( joinHucRrkWip = st_join(joinHucRrk, wip_ab, largest=TRUE) )
```


```{r}
( aoi = joinHucRrkWip %>% filter(RRK_Region %in% c("Central Coast Region", "North Coast Region", "South Coast Region", "Sierra Nevada Region"))
)
```


```{r}
aoi
```


# Write Shp to file
```{r}
st_write(aoi, "../outputs/HucsRrkWip.shp", driver="ESRI Shapefile")
```




# Plot SN and WIP
```{r}
sn = aoi %>% filter(RRK_Region=="Sierra Nevada Region")
cc = aoi %>% filter(RRK_Region=="Central Coast Region")
```

```{r}
plot(st_geometry(rrk))
plot(st_geometry(sn),col="red", add=TRUE)
```

```{r}
plot(st_geometry(rrk))
plot(st_geometry(cc),col="red", add=TRUE)
```