---
title: "Veg Area Grids"
author: "Anna Talucci"
date: "8/23/2023"
output: html_document
---



# Packages
```{r}
library(tidyverse)
library(sf)
library(viridis)
```

# Data
## Tx area
```{r}
cc = read.csv("../data/VegGrid/ccVegAreaGrid.csv")
sc = read.csv("../data/VegGrid/scVegAreaGrid.csv")
```

```{r}
cc30 = read.csv("../data/VegGrid/ccVegAreaGrid30.csv")
sc30 = read.csv("../data/VegGrid/scVegAreaGrid30.csv")
```

```{r}
ccTx = read.csv("../data/VegGrid/ccGridTreat.csv")
```

```{r}
ccTx = read.csv("../data/VegGrid/ccGridTx.csv")
scTx = read.csv("../data/VegGrid/scGridTx.csv")
ccProj = read.csv("../data/VegGrid/ccGridTxProj.csv")
scProj = read.csv("../data/VegGrid/scGridTxProj.csv")
```

```{r}
ccHucs = read.csv("../data/VegGrid/ccGridTxHuc.csv")
scHucs = read.csv("../data/VegGrid/scGridTxHuc.csv")
```
ccGridTreat
```{r}
head(cc)
head(ccPx)
head(sc)
head(sc30)
```

```{r}
head(ccTx)
head(ccProj)
head(scTx)
head(scProj)
```

```{r}
head(ccHucs)
head(scHucs)
```
# Area total

```{r}
cc %>% summarise(totalSqm = sum(vegSum),
                 totalSqkm = (totalSqm/1e6),
                 toalAcres = (totalSqkm*247.1))
```

```{r}
ccPx %>% summarise(totalSqm = sum(sum),
                 totalSqkm = (totalSqm/1e6),
                 toalAcres = (totalSqkm*247.1))
```
```{r}
sc %>% summarise(totalSqm = sum(vegSum),
                 totalSqkm = (totalSqm/1000000),
                 toalAcres = (totalSqkm*247.1))
```

```{r}
ccTx %>% summarise(total = sum(treatAcres))
ccProj %>% summarise(total = sum(treatAcres))
```

```{r}
scTx %>% summarise(total = sum(treatAcres))
scProj %>% summarise(total = sum(treatAcres))
```

```{r}
ccHucs %>% summarise(total = sum(treatAcres))
scHucs %>% summarise(total = sum(treatAcres))
```