---
title: "Veg Treatment Types"
output: html_document
---

```{r clearEnvironment, include=FALSE}
rm(list=ls())
```

```{r globalOptions, include=FALSE}
options(scipen=999) #Prevent scientific notation of numeric values; use =0 to reset
```

# Overview

This script is filtering treatable vegetation types and printing those values as a list for each RRK that is copied and pasted into EE script.

# Packages
```{r}
library(tidyverse)
```

# Data
```{r}
data = read.csv("../data/WHRVegTypes/WhrVegTypesTreatments.csv")
```

```{r}
dataHS = read.csv("../data/WHRVegTypes/WHRVegTypesHardSoft.csv")
```

# Data overview
```{r}
head(dataHS)
```
```{r}
unique(dataHS$region)
```
# Filter

## For treatments by RRK

## SC
```{r}
( 
  sc = dataHS %>% filter(region=="sc") %>% filter(treatment==1) %>% arrange(value)
)
```
```{r}
unique(sc$value)
```
```{r}
cat(paste0(sprintf('%s', unique(sc$value)), collapse = ", "))
```
## NC
```{r}
( 
  nc = dataHS %>% filter(region=="nc") %>% filter(treatment==1) %>% arrange(value)
)
```
```{r}
unique(nc$value)
```
```{r}
cat(paste0(sprintf('%s', unique(nc$value)), collapse = ", "))
```
## CC
```{r}
( 
  cc = dataHS %>% filter(region=="cc") %>% filter(treatment==1) %>% arrange(value)
)
```
```{r}
unique(cc$value)
```
```{r}
cat(paste0(sprintf('%s', unique(cc$value)), collapse = ", "))
```
## SN
```{r}
( 
  sn = dataHS %>% filter(region=="sn") %>% filter(treatment==1) %>% arrange(value)
)
```

```{r}
unique(sn$value)
```
```{r}
cat(paste0(sprintf('%s', unique(sn$value)), collapse = ", "))
```

# Get unique values for veg type
```{r}
unique(sc$value)
```
```{r}
cat(paste0(sprintf('%s', unique(sc$value)), collapse = ", "))
```

```{r}
unique(nc$value)
```

```{r}
cat(paste0(sprintf('%s', unique(nc$value)), collapse = ", "))
```

```{r}
unique(cc$value)
```
```{r}
cat(paste0(sprintf('%s', unique(cc$value)), collapse = ", "))
```

```{r}
unique(sn$value)
```
```{r}
cat(paste0(sprintf('%s', unique(sn$value)), collapse = ", "))
```


# Veg type

```{r}
unique(dataHS$type)
```
## New
```{r}
( softwood = dataHS %>% 
    filter(treatment==1) %>%
  filter(type =="Softwood") %>% 
    arrange(value)
)
```

```{r}
unique(softwood$value)
```
```{r}
cat(paste0(sprintf('%s', unique(softwood$value)), collapse = ", "))
```

```{r}
( hardwood = dataHS %>% 
    filter(treatment==1) %>%
  filter(type =="Hardwood") %>% 
    arrange(value)
)
```

```{r}
unique(hardwood$value)
```
```{r}
cat(paste0(sprintf('%s', unique(hardwood$value)), collapse = ", "))
```

```{r}
( shrub = dataHS %>% 
    filter(treatment==1) %>%
  filter(type =="Shrub") %>% 
    arrange(value)
  
)
```

```{r}
unique(shrub$value)
```
```{r}
cat(paste0(sprintf('%s', unique(shrub$value)), collapse = ", "))
```

```{r}
( herb = dataHS %>% 
    filter(treatment==1) %>%
  filter(type =="Herb") %>% 
    arrange(value)
)
```

```{r}
unique(herb$value)
```

```{r}
cat(paste0(sprintf('%s', unique(herb$value)), collapse = ", "))
```

## Old
```{r}
( tree = data %>% 
  filter(type =="Tree") %>% 
    arrange(value)
)
```

```{r}
unique(tree$value)
```
```{r}
cat(paste0(sprintf('%s', unique(tree$value)), collapse = ", "))
```

```{r}
( shrub = data %>% 
  filter(type =="Shrub") %>% 
    arrange(value)
  
)
```

```{r}
unique(shrub$value)
```
```{r}
cat(paste0(sprintf('%s', unique(shrub$value)), collapse = ", "))
```

```{r}
( herb = data %>% 
  filter(type =="Herb") %>% 
    arrange(value)
)
```

```{r}
unique(herb$value)
```

```{r}
cat(paste0(sprintf('%s', unique(herb$value)), collapse = ", "))
```