---
title: "RRK Summary Area for Herb Shrub Tree"
output: html_document
---

# Overview
This script takes the CSV output from EE and calculates the percent treatable herb, shrub, hardwood, and softwood by RRK.


# Packages
```{r}
library(tidyverse)
library(skimr)
```

# Data
```{r}
allHucs = read.csv("../data/vegType/AllHucsHerbShrubHardSoft.csv")
```
2,944 rows
```{r}
glimpse(allHucs)
```

```{r}
head(allHucs)
```

```{r}
tail(allHucs)
```
```{r}
unique(allHucs$RRK_Region)
unique(allHucs$WIPGeoNam)
```




# By HUC and RRK And WIP

```{r}
( allHucs1 = allHucs %>% 
    dplyr::select(RRK_Region, WIPGeoNam, herbsumsqkm, shrubsumsqkm, hardwoodsumsqkm, softwoodsumsqkm, vegsumsqkm) %>%
  mutate(herbsumsqkm = round(herbsumsqkm, 2)) %>%
  mutate(shrubsumsqkm = round(shrubsumsqkm, 2)) %>%
  mutate(hardwoodsumsqkm = round(hardwoodsumsqkm, 2)) %>%
  mutate(softwoodsumsqkm = round(softwoodsumsqkm, 2)) %>%
   mutate(vegsumsqkm = round(vegsumsqkm, 2)) 
    
)

```

```{r}
( allHucsPrct = allHucs1 %>% 
    group_by(RRK_Region)  %>%
  summarise(across(c(herbsumsqkm, shrubsumsqkm, hardwoodsumsqkm, softwoodsumsqkm, vegsumsqkm),sum),
            .groups = 'drop') %>%
  as.data.frame() %>%
  mutate(herbPrct = round((herbsumsqkm/vegsumsqkm)*100, 2)) %>%
  mutate(shrubPrct = round((shrubsumsqkm/vegsumsqkm)*100, 2)) %>%
  mutate(hardwoodPrct = round((hardwoodsumsqkm/vegsumsqkm)*100, 2)) %>%
  mutate(softwoodPrct = round((softwoodsumsqkm/vegsumsqkm)*100, 2))
)
```

```{r}
write.csv(allHucsPrct, "../outputs/AllHucsPercentHSTbyRRK.csv")
```

# by WIP
```{r}
( SNHucsArea = allHucs1 %>% 
    filter(RRK_Region=="Sierra Nevada Region")  %>%
    group_by(WIPGeoNam) %>%
  summarise(across(c(herbsumsqkm, shrubsumsqkm, hardwoodsumsqkm, softwoodsumsqkm, vegsumsqkm),sum),
            .groups = 'drop') %>%
  as.data.frame() %>%
  mutate(herbPrct = round((herbsumsqkm/vegsumsqkm)*100, 2)) %>%
  mutate(shrubPrct = round((shrubsumsqkm/vegsumsqkm)*100, 2)) %>%
  mutate(hardwoodPrct = round((hardwoodsumsqkm/vegsumsqkm)*100, 2)) %>%
  mutate(softwoodPrct = round((softwoodsumsqkm/vegsumsqkm)*100, 2))
)
```

```{r}
write.csv(SNHucsArea, "../outputs/SNHucsPercentHSTbyWIP.csv")
```


